SEO-179239-Redirect-Links-TS
syncfusion-content/ej2-calendar-docs pull request #37
Opened 2024-01-16 09:58 UTC by berylouma

Hello,

I have worked on links with redirects.

Regards,
Beryl.

2024-01-16 09:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-179239-Redirect-Links-TS](https://ci.syncfusion.com/job/Content/job/ej2-calendar-docs/4/console)**

2024-01-16 10:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-179239-Redirect-Links-TS](https://ci.syncfusion.com/job/Content/job/ej2-calendar-docs/4/)<br/>**

2024-01-17 13:41 UTC, Yvone-Atieno requested changes
Commented

2024-01-17 13:41 UTC, Yvone-Atieno commented on ej2-javascript/datepicker/ts/getting-started.md
> +This section briefly explains how to create a simple [JavaScript DatePicker](https://www.syncfusion.com/javascript-controls/js-datepicker) component and configure its available functionalities in Typ
Check JavaScript DatePicker link

2024-01-17 13:47 UTC, berylouma commented on ej2-javascript/datepicker/ts/getting-started.md
> +This section briefly explains how to create a simple [JavaScript DatePicker](https://www.syncfusion.com/javascript-controls/js-datepicker) component and configure its available functionalities in Typ
Corrected

2024-01-17 13:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-179239-Redirect-Links-TS](https://ci.syncfusion.com/job/Content/job/ej2-calendar-docs/7/)<br/>**

2024-01-17 13:49 UTC, Yvone-Atieno approved these changes
Approved

2024-01-19 13:30 UTC, merged